// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJkDwPMbIUeij-6hoHys_jFW0RKS4JTtE',
    appId: '1:711522983056:web:6689f594c40a1205094c15',
    messagingSenderId: '711522983056',
    projectId: 'realmofvalorapp',
    authDomain: 'realmofvalorapp.firebaseapp.com',
    storageBucket: 'realmofvalorapp.appspot.com',
    measurementId: 'G-465898394',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkDwPMbIUeij-6hoHys_jFW0RKS4JTtE',
    appId: '1:711522983056:android:7c6c21c1d033e74a094c15',
    messagingSenderId: '711522983056',
    projectId: 'realmofvalorapp',
    storageBucket: 'realmofvalorapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJkDwPMbIUeij-6hoHys_jFW0RKS4JTtE',
    appId: '1:711522983056:ios:d735f90daf370c2c094c15',
    messagingSenderId: '711522983056',
    projectId: 'realmofvalorapp',
    storageBucket: 'realmofvalorapp.appspot.com',
    iosBundleId: 'com.TomReynolds.realmofvalor.apple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJkDwPMbIUeij-6hoHys_jFW0RKS4JTtE',
    appId: '1:711522983056:ios:d735f90daf370c2c094c15',
    messagingSenderId: '711522983056',
    projectId: 'realmofvalorapp',
    storageBucket: 'realmofvalorapp.appspot.com',
    iosBundleId: 'com.TomReynolds.realmofvalor.apple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJkDwPMbIUeij-6hoHys_jFW0RKS4JTtE',
    appId: '1:711522983056:web:6689f594c40a1205094c15',
    messagingSenderId: '711522983056',
    projectId: 'realmofvalorapp',
    storageBucket: 'realmofvalorapp.appspot.com',
  );
}
